import { Orchard } from "../interface/orchardInterface";
import { User } from "../interface/userInterface";
import { ServiceTypeResponse, StatusResponse, CropOption } from "../interface/dropdownInterface";

import { DurianStatus, OrchardType, UserRole, CropCategory } from "./enum";

export const MOCK_OWNER: User = {
	id: "owner1",
	email: "owner@durian.com",
	name: "ลุงดำ เจ้าของสวน",
	role: UserRole.Owner,
};

export const MOCK_SERVICE_TYPES: ServiceTypeResponse[] = Object.values(OrchardType).map((type) => ({
	id: type,
}));

export const MOCK_STATUSES: StatusResponse[] = Object.values(DurianStatus).map((status) => ({
	id: status,
}));

export const MOCK_CROPS: CropOption[] = [
	{ id: "mangosteen", label: "มังคุด (Mangosteen)", category: CropCategory.Fruit },
	{ id: "rambutan", label: "เงาะ (Rambutan)", category: CropCategory.Fruit },
	{ id: "longan", label: "ลำไย (Longan)", category: CropCategory.Fruit },
	{ id: "banana", label: "กล้วย (Banana)", category: CropCategory.Fruit },
	{ id: "papaya", label: "มะละกอ (Papaya)", category: CropCategory.Fruit },
	{ id: "chili", label: "พริก (Chili)", category: CropCategory.Vegetable },
	{ id: "corn", label: "ข้าวโพด (Corn)", category: CropCategory.Vegetable },
	{ id: "kale", label: "คะน้า (Kale)", category: CropCategory.Vegetable },
	{ id: "eggplant", label: "มะเขือ (Eggplant)", category: CropCategory.Vegetable },
];

export const MOCK_ORCHARDS: Orchard[] = [
	// Eastern (Existing)
	{
		id: 1,
		name: "สวนดีมีชัย",
		description: "ทุเรียนหมอนทองแท้ อร่อย หวานมัน รับประกันคุณภาพจากสวน",
		history:
			"สวนทุเรียนลุงดำก่อตั้งขึ้นเมื่อปี พ.ศ. 2535 โดยคุณลุงดำ ผู้มีความรักในการปลูกทุเรียน เริ่มต้นจากพื้นที่เพียง 10 ไร่ ปัจจุบันขยายเป็น 50 ไร่ ด้วยความใส่ใจในการดูแลแบบเกษตรอินทรีย์ ทำให้ได้ผลผลิตที่มีคุณภาพและรสชาติเป็นเอกลักษณ์",
		types: [OrchardType.Sell, OrchardType.Tour, OrchardType.Cafe, OrchardType.Stay],
		status: DurianStatus.Available,
		lat: 13.123,
		lng: 101.456,
		ownerId: "owner1",
		address:
			"268 ตึก CU I House ห้อง 1440 จุฬาลงกรณ์ ซอย 9 ถนนจรัสเมือง แขวงวังใหม่ เขตปทุมวัน จังหวัดกรุงเทพฯ 10330 ",
		phoneNumber: "082-114-4010",
		isMixedAgro: true,
		additionalCrops: ["mangosteen", "rambutan"],
		socialMedia: {
			facebook: "https://facebook.com/thejing.jerry",
			instagram: "https://instagram.com/thejing.jerry",
			line: "https://line.me/ti/p/~jing.jerry",
			tiktok: "https://www.tiktok.com/@_j.ksd_",
			youtube: "https://www.youtube.com/@kritsadalimsripraphan788",
		},
		images: [
			"https://picsum.photos/400/300?random=1",
			"https://picsum.photos/400/300?random=11",
		],
		videos: ["https://youtu.be/IAMyWV6Fo6c?si=NU71SdfYXyy9eY9g"],
		hasPackage: true,
		packages: [
			{
				id: "pkg1",
				name: "บุฟเฟต์ทุเรียน อิ่มไม่อั้น",
				price: 399,
				duration: 2,
				includes:
					"ทานทุเรียนหมอนทอง, ชะนี, ก้านยาว ได้ไม่อั้น พร้อมผลไม้ตามฤดูกาลอื่นๆ น้ำดื่มสมุนไพรฟรี",
				startDate: "2024-04-01",
				endDate: "2024-06-30",
				images: ["https://picsum.photos/400/300?random=101"],
			},
		],
		hasAccommodation: true,
		accommodations: [
			{
				id: "acc1",
				name: "บ้านพักริมคลอง (2 ท่าน)",
				price: 1200,
				quantity: 3,
				images: ["https://picsum.photos/400/300?random=22"],
			},
			{
				id: "acc2",
				name: "บ้านครอบครัวใหญ่ (6 ท่าน)",
				price: 3500,
				quantity: 1,
				images: ["https://picsum.photos/400/300?random=23"],
			},
		],
	},
	{
		id: 2,
		name: "สวนดีมีชัย 2",
		description: "ทุเรียนหมอนทองแท้ อร่อย หวานมัน รับประกันคุณภาพจากสวน",
		history:
			"สวนทุเรียนลุงดำก่อตั้งขึ้นเมื่อปี พ.ศ. 2535 โดยคุณลุงดำ ผู้มีความรักในการปลูกทุเรียน เริ่มต้นจากพื้นที่เพียง 10 ไร่ ปัจจุบันขยายเป็น 50 ไร่ ด้วยความใส่ใจในการดูแลแบบเกษตรอินทรีย์ ทำให้ได้ผลผลิตที่มีคุณภาพและรสชาติเป็นเอกลักษณ์",
		types: [OrchardType.Sell, OrchardType.Tour],
		status: DurianStatus.Available,
		lat: 13.123,
		lng: 101.456,
		ownerId: "owner1",
		address:
			"268 ตึก CU I House ห้อง 1440 จุฬาลงกรณ์ ซอย 9 ถนนจรัสเมือง แขวงวังใหม่ เขตปทุมวัน จังหวัดกรุงเทพฯ 10330 ",
		phoneNumber: "082-114-4010",
		isMixedAgro: true,
		additionalCrops: ["mangosteen", "rambutan"],
		socialMedia: {
			facebook: "https://facebook.com/thejing.jerry",
			instagram: "https://instagram.com/thejing.jerry",
		},
		images: [
			"https://picsum.photos/400/300?random=2",
			"https://picsum.photos/400/300?random=21",
		],
		videos: ["https://youtu.be/IAMyWV6Fo6c?si=NU71SdfYXyy9eY9g"],
		hasPackage: true,
		packages: [
			{
				id: "pkg1",
				name: "บุฟเฟต์ทุเรียน อิ่มไม่อั้น",
				price: 399,
				duration: 2,
				includes:
					"ทานทุเรียนหมอนทอง, ชะนี, ก้านยาว ได้ไม่อั้น พร้อมผลไม้ตามฤดูกาลอื่นๆ น้ำดื่มสมุนไพรฟรี",
				startDate: "2024-04-01",
				endDate: "2024-06-30",
				images: ["https://picsum.photos/400/300?random=101"],
			},
		],
		hasAccommodation: true,
		accommodations: [
			{
				id: "acc1",
				name: "บ้านพักริมคลอง (2 ท่าน)",
				price: 1200,
				quantity: 3,
				images: ["https://picsum.photos/400/300?random=22"],
			},
			{
				id: "acc2",
				name: "บ้านครอบครัวใหญ่ (6 ท่าน)",
				price: 3500,
				quantity: 1,
				images: ["https://picsum.photos/400/300?random=23"],
			},
		],
	},
	{
		id: 3,
		name: "บ้านสวนคุณยาย",
		description: "บรรยากาศดี มีโฮมสเตย์ พร้อมอาหารพื้นบ้านและบุฟเฟต์ทุเรียน",
		history:
			"เดิมเป็นบ้านพักตากอากาศของครอบครัว ก่อนจะปรับปรุงเป็นโฮมสเตย์เพื่อต้อนรับนักท่องเที่ยวที่อยากสัมผัสวิถีชีวิตชาวสวนจันทบุรีแบบดั้งเดิม",
		types: [OrchardType.Stay, OrchardType.Cafe, OrchardType.Sell],
		status: DurianStatus.Low,
		lat: 13.155,
		lng: 101.488,
		ownerId: "owner1",
		address: "45 หมู่ 5 ต.พลิ้ว จ.จันทบุรี",
		phoneNumber: "089-987-6543",
		isMixedAgro: false,
		additionalCrops: [],
		socialMedia: {
			facebook: "https://facebook.com",
			instagram: "https://instagram.com",
		},
		images: [
			"https://picsum.photos/400/300?random=3",
			"https://picsum.photos/400/300?random=31",
		],
		hasAccommodation: true,
		accommodations: [
			{
				id: "acc1",
				name: "บ้านพักริมคลอง (2 ท่าน)",
				price: 1200,
				quantity: 3,
				images: ["https://picsum.photos/400/300?random=22"],
			},
			{
				id: "acc2",
				name: "บ้านครอบครัวใหญ่ (6 ท่าน)",
				price: 3500,
				quantity: 1,
				images: ["https://picsum.photos/400/300?random=23"],
			},
		],
		hasPackage: true,
		packages: [
			{
				id: "pkg2-1",
				name: "Workshop กวนทุเรียนโบราณ",
				price: 350,
				duration: 3,
				includes:
					"เรียนรู้วิธีการเลือกเนื้อทุเรียน การกวนแบบโบราณ พร้อมรับทุเรียนกวนฝีมือตัวเองกลับบ้าน 1 กระปุก",
				startDate: "2024-05-01",
				endDate: "2024-07-31",
				images: ["https://picsum.photos/400/300?random=102"],
			},
		],
	},
	{
		id: 4,
		name: "Durian Valley Cafe",
		description: "คาเฟ่กลางสวนทุเรียน มุมถ่ายรูปเยอะมาก กาแฟดี เค้กทุเรียนอร่อย",
		types: [OrchardType.Cafe, OrchardType.Tour],
		status: DurianStatus.Reserved,
		lat: 13.2,
		lng: 101.5,
		ownerId: "owner1",
		address: "88 ถนนสุขุมวิท จ.ตราด",
		phoneNumber: "02-111-2222",
		isMixedAgro: false,
		additionalCrops: [],
		socialMedia: {
			instagram: "https://instagram.com",
			tiktok: "https://tiktok.com",
		},
		images: ["https://picsum.photos/400/300?random=4"],
	},
	// Northern
	{
		id: 5,
		name: "สวนลับแลเมืองงาม",
		description: "ทุเรียนหลงลับแล หลินลับแล ต้นตำรับแท้ๆ จากอุตรดิตถ์",
		types: [OrchardType.Sell, OrchardType.Tour],
		status: DurianStatus.Available,
		lat: 17.652878,
		lng: 100.038561,
		ownerId: "owner5",
		address: "ต.แม่พูล อ.ลับแล จ.อุตรดิตถ์",
		phoneNumber: "089-111-1111",
		isMixedAgro: false,
		additionalCrops: [],
		images: ["https://picsum.photos/400/300?random=5"],
	},
	{
		id: 6,
		name: "ไร่ภูผา เชียงราย",
		description: "ทุเรียนเมืองหนาว รสชาติเป็นเอกลักษณ์ วิวภูเขาสวยงาม",
		types: [OrchardType.Tour, OrchardType.Stay],
		status: DurianStatus.Reserved,
		lat: 19.927239,
		lng: 99.859665,
		ownerId: "owner6",
		address: "ดอยแม่สลอง จ.เชียงราย",
		phoneNumber: "089-222-2222",
		isMixedAgro: true,
		additionalCrops: ["kale", "corn"],
		socialMedia: {
			youtube: "https://youtube.com",
		},
		images: ["https://picsum.photos/400/300?random=6"],
		hasAccommodation: true,
		accommodations: [
			{
				id: "acc6-1",
				name: "เต็นท์กระโจมวิวเขา",
				price: 1500,
				quantity: 5,
				images: ["https://picsum.photos/400/300?random=61"],
			},
		],
	},
	{
		id: 7,
		name: "สวนแม่กำปอง ฮิลล์",
		description: "คาเฟ่และสวนทุเรียนกลางหุบเขา อากาศเย็นตลอดปี",
		types: [OrchardType.Cafe, OrchardType.Tour],
		status: DurianStatus.Low,
		lat: 18.865421,
		lng: 99.348633,
		ownerId: "owner7",
		address: "แม่กำปอง อ.แม่ออน จ.เชียงใหม่",
		phoneNumber: "089-333-3333",
		isMixedAgro: false,
		additionalCrops: [],
		images: ["https://picsum.photos/400/300?random=7"],
	},
	{
		id: 8,
		name: "น่าน วัลเล่ย์ ฟาร์ม",
		description: "สวนเกษตรผสมผสาน ทุเรียนคุณภาพดีจากดินเมืองน่าน",
		types: [OrchardType.Sell],
		status: DurianStatus.Out,
		lat: 19.186641,
		lng: 100.798122,
		ownerId: "owner8",
		address: "อ.ท่าวังผา จ.น่าน",
		phoneNumber: "089-444-4444",
		isMixedAgro: true,
		additionalCrops: ["corn", "chili"],
		images: ["https://picsum.photos/400/300?random=8"],
	},
	// Northeastern
	{
		id: 9,
		name: "สวนทุเรียนภูเขาไฟศรีสะเกษ",
		description: "ทุเรียนภูเขาไฟ เปลือกบาง เนื้อแห้ง กรอบนอกนุ่มใน",
		types: [OrchardType.Sell, OrchardType.Tour],
		status: DurianStatus.Available,
		lat: 14.939223,
		lng: 104.571556,
		ownerId: "owner9",
		address: "อ.กันทรลักษ์ จ.ศรีสะเกษ",
		phoneNumber: "089-555-5555",
		isMixedAgro: false,
		additionalCrops: [],
		socialMedia: {
			facebook: "https://facebook.com",
			line: "https://line.me",
		},
		images: ["https://picsum.photos/400/300?random=9"],
	},
	{
		id: 10,
		name: "โอโซน ปากช่อง",
		description: "แหล่งเรียนรู้และท่องเที่ยวเชิงเกษตร ปากช่อง โคราช",
		types: [OrchardType.Tour, OrchardType.Cafe],
		status: DurianStatus.Reserved,
		lat: 14.654512,
		lng: 101.536342,
		ownerId: "owner10",
		address: "ต.หนองน้ำแดง อ.ปากช่อง จ.นครราชสีมา",
		phoneNumber: "089-666-6666",
		isMixedAgro: true,
		additionalCrops: ["eggplant", "chili"],
		images: ["https://picsum.photos/400/300?random=10"],
	},
	// Central
	{
		id: 11,
		name: "มวกเหล็ก การ์เด้น",
		description: "สวนผลไม้ใกล้กรุง ทุเรียนและสระบุรีเลื่องชื่อ",
		types: [OrchardType.Sell, OrchardType.Cafe],
		status: DurianStatus.Available,
		lat: 14.628434,
		lng: 101.166415,
		ownerId: "owner12",
		address: "อ.มวกเหล็ก จ.สระบุรี",
		phoneNumber: "089-888-8888",
		isMixedAgro: false,
		additionalCrops: [],
		images: ["https://picsum.photos/400/300?random=12"],
	},
	{
		id: 12,
		name: "สวนลุงหมู นครนายก",
		description: "ทุเรียนสาริกา และผลไม้นานาชนิด ใกล้น้ำตกนางรอง",
		types: [OrchardType.Tour, OrchardType.Sell],
		status: DurianStatus.Out,
		lat: 14.288296,
		lng: 101.26578,
		ownerId: "owner13",
		address: "ต.สาริกา อ.เมือง จ.นครนายก",
		phoneNumber: "089-999-9999",
		isMixedAgro: true,
		additionalCrops: ["mangosteen", "longan"],
		images: ["https://picsum.photos/400/300?random=13"],
	},
	{
		id: 13,
		name: "ป่าละอู ออแกนิค",
		description: "ทุเรียนป่าละอู พระราชทาน เนื้อหนา รสเข้มข้น",
		types: [OrchardType.Sell],
		status: DurianStatus.Available,
		lat: 12.535031,
		lng: 99.471676,
		ownerId: "owner14",
		address: "ต.ห้วยสัตว์ใหญ่ อ.หัวหิน จ.ประจวบคีรีขันธ์",
		phoneNumber: "089-000-0000",
		isMixedAgro: false,
		additionalCrops: [],
		images: ["https://picsum.photos/400/300?random=14"],
	},
];
