import { Orchard } from "../interface/orchardInterface";
import { User } from "../interface/userInterface";
import { ServiceTypeResponse, StatusResponse, CropOption } from "../interface/dropdownInterface";

import { DurianStatus, OrchardType, UserRole, CropCategory } from "./enum";

export const MOCK_OWNER: User = {
	id: "owner1",
	email: "owner@durian.com",
	name: "ลุงดำ เจ้าของสวน",
	role: UserRole.Owner,
};

export const MOCK_SERVICE_TYPES: ServiceTypeResponse[] = Object.values(OrchardType).map((type) => ({
	id: type,
}));

export const MOCK_STATUSES: StatusResponse[] = Object.values(DurianStatus).map((status) => ({
	id: status,
}));

export const MOCK_CROPS: CropOption[] = [
	{ id: "mangosteen", label: "มังคุด (Mangosteen)", category: CropCategory.Fruit },
	{ id: "rambutan", label: "เงาะ (Rambutan)", category: CropCategory.Fruit },
	{ id: "longan", label: "ลำไย (Longan)", category: CropCategory.Fruit },
	{ id: "banana", label: "กล้วย (Banana)", category: CropCategory.Fruit },
	{ id: "papaya", label: "มะละกอ (Papaya)", category: CropCategory.Fruit },
	{ id: "mango", label: "มะม่วง (Mango)", category: CropCategory.Fruit },
	{ id: "coconut", label: "มะพร้าว (Coconut)", category: CropCategory.Fruit },
	{ id: "pineapple", label: "สับปะรด (Pineapple)", category: CropCategory.Fruit },
	{ id: "salak", label: "สละ (Salak)", category: CropCategory.Fruit },
	{ id: "longkong", label: "ลองกอง (Longkong)", category: CropCategory.Fruit },
	{ id: "roseapple", label: "ชมพู่ (Rose Apple)", category: CropCategory.Fruit },
	{ id: "chili", label: "พริก (Chili)", category: CropCategory.Vegetable },
	{ id: "corn", label: "ข้าวโพด (Corn)", category: CropCategory.Vegetable },
	{ id: "kale", label: "คะน้า (Kale)", category: CropCategory.Vegetable },
	{ id: "eggplant", label: "มะเขือ (Eggplant)", category: CropCategory.Vegetable },
	{ id: "lime", label: "มะนาว (Lime)", category: CropCategory.Vegetable },
	{ id: "cucumber", label: "แตงกวา (Cucumber)", category: CropCategory.Vegetable },
	{ id: "morningglory", label: "ผักบุ้ง (Morning Glory)", category: CropCategory.Vegetable },
];

export const MOCK_ORCHARDS: Orchard[] = [
	{
		id: 1,
		name: "สวนดีมีชัย",
		description: "ทุเรียนหมอนทองแท้ อร่อย หวานมัน รับประกันคุณภาพจากสวน",
		history:
			"สวนทุเรียนลุงดำก่อตั้งขึ้นเมื่อปี พ.ศ. 2535 โดยคุณลุงดำ ผู้มีความรักในการปลูกทุเรียน เริ่มต้นจากพื้นที่เพียง 10 ไร่ ปัจจุบันขยายเป็น 50 ไร่ ด้วยความใส่ใจในการดูแลแบบเกษตรอินทรีย์ ทำให้ได้ผลผลิตที่มีคุณภาพและรสชาติเป็นเอกลักษณ์",
		types: [OrchardType.Sell, OrchardType.Tour, OrchardType.Cafe, OrchardType.Stay],
		status: DurianStatus.Available,
		lat: 13.123,
		lng: 101.456,
		ownerId: "owner1",
		address:
			"268 ตึก CU I House ห้อง 1440 จุฬาลงกรณ์ ซอย 9 ถนนจรัสเมือง แขวงวังใหม่ เขตปทุมวัน จังหวัดกรุงเทพฯ 10330 ",
		isMixedAgro: true,
		additionalCrops: ["mangosteen", "rambutan"],
		socialMedia: {
			facebook: "https://facebook.com/thejing.jerry",
			instagram: "https://instagram.com/thejing.jerry",
			line: "https://line.me/ti/p/~jing.jerry",
			tiktok: "https://www.tiktok.com/@_j.ksd_",
			youtube: "https://www.youtube.com/@kritsadalimsripraphan788",
		},
		images: [
			"https://picsum.photos/400/300?random=1",
			"https://picsum.photos/400/300?random=11",
			"https://picsum.photos/400/300?random=21",
			"https://picsum.photos/400/300?random=31",
			"https://picsum.photos/400/300?random=41",
			"https://picsum.photos/400/300?random=51",
			"https://picsum.photos/400/300?random=61",
			"https://picsum.photos/400/300?random=71",
			"https://picsum.photos/400/300?random=81",
			"https://picsum.photos/400/300?random=91",
			"https://picsum.photos/400/300?random=101",
			"https://picsum.photos/400/300?random=111",
			"https://picsum.photos/400/300?random=121",
			"https://picsum.photos/400/300?random=131",
			"https://picsum.photos/400/300?random=141",
			"https://picsum.photos/400/300?random=151",
		],
		videos: [
			"https://youtu.be/IAMyWV6Fo6c?si=NU71SdfYXyy9eY9g",
			"https://youtu.be/ZGgFzQXfvmY?si=yfzec32taKKH_a3J",
			"https://youtu.be/2_vIml6LTAw?si=zxgSmv8SsW923Die",
		],
		hasPackage: true,
		packages: [
			{
				id: "pkg1",
				name: "บุฟเฟต์ทุเรียน อิ่มไม่อั้น",
				price: 399,
				duration: 2,
				includes:
					"ทานทุเรียนหมอนทอง, ชะนี, ก้านยาว ได้ไม่อั้น พร้อมผลไม้ตามฤดูกาลอื่นๆ น้ำดื่มสมุนไพรฟรี",
				startDate: "2024-04-01",
				endDate: "2024-06-30",
				images: ["https://picsum.photos/400/300?random=101"],
			},
			{
				id: "pkg2",
				name: "บุฟเฟต์ทุเรียน",
				price: 299,
				duration: 4,
				includes:
					"ทานทุเรียนหมอนทอง, ชะนี, ก้านยาว ได้ไม่อั้น พร้อมผลไม้ตามฤดูกาลอื่นๆ น้ำดื่มสมุนไพรฟรี",
				startDate: "2025-04-01",
				endDate: "2025-06-30",
				images: ["https://picsum.photos/400/300?random=101"],
			},
		],
		hasAccommodation: true,
		accommodations: [
			{
				id: "acc1",
				name: "บ้านพักริมคลอง (2 ท่าน)",
				price: 1200,
				quantity: 3,
				images: ["https://picsum.photos/400/300?random=22"],
			},
			{
				id: "acc2",
				name: "บ้านครอบครัวใหญ่ (6 ท่าน)",
				price: 3500,
				quantity: 1,
				images: ["https://picsum.photos/400/300?random=23"],
			},
		],
	},
	{
		id: 2,
		name: "สวนลุงแดง ระยองฮิ",
		description:
			"บุฟเฟต์ผลไม้และทุเรียนเกรดพรีเมียม สวรรค์ของคนรักทุเรียน กินไม่อั้น ไม่จำกัดเวลา บรรยากาศร่มรื่นใต้ร่มเงาไม้",
		history:
			"เปิดให้บริการมากว่า 10 ปี เป็นสวนแรกๆ ที่ทำบุฟเฟต์ในย่านตะพง ลุงแดงคัดทุเรียนเองกับมือทุกลูก รับประกันคุณภาพ ถ้าไม่ดีเปลี่ยนให้ทันที เริ่มต้นจากทำสวนผสมผสานจนมาเน้นทุเรียนเป็นหลัก",
		types: [OrchardType.Sell, OrchardType.Tour],
		status: DurianStatus.Low,
		lat: 12.6812,
		lng: 101.2815,
		ownerId: "owner2",
		address: "123 หมู่ 4 ต.ตะพง อ.เมือง จ.ระยอง 21000",
		isMixedAgro: true,
		additionalCrops: ["mangosteen", "salak", "longkong"],
		socialMedia: {
			facebook: "https://facebook.com/suanlungdaeng",
		},
		images: [
			"https://picsum.photos/400/300?random=201",
			"https://picsum.photos/400/300?random=202",
			"https://picsum.photos/400/300?random=203",
			"https://picsum.photos/400/300?random=204",
			"https://picsum.photos/400/300?random=205",
			"https://picsum.photos/400/300?random=206",
			"https://picsum.photos/400/300?random=207",
			"https://picsum.photos/400/300?random=208",
			"https://picsum.photos/400/300?random=209",
			"https://picsum.photos/400/300?random=210",
			"https://picsum.photos/400/300?random=211",
			"https://picsum.photos/400/300?random=212",
		],
		videos: [],
		hasPackage: true,
		packages: [
			{
				id: "pkg_buffet_1",
				name: "Super Premium Buffet 2026",
				price: 890,
				duration: 3,
				includes:
					"ทุเรียนหมอนทอง, ชะนี, ก้านยาว (ตามรอบที่สุก), มังคุดคัดเกรด, ลองกอง, สละสุมาลี, ข้าวเหนียวทุเรียน, ขนมจีนน้ำยาปูสูตรเด็ดคุณยาย, ไอศกรีมทุเรียนโฮมเมด",
				startDate: "2026-04-15",
				endDate: "2026-07-15",
				images: ["https://picsum.photos/400/300?random=201"],
			},
		],
		hasAccommodation: false,
		accommodations: [],
	},
	{
		id: 3,
		name: "บ้านสวนจันทิมา โฮมสเตย์",
		description:
			"พักผ่อนท่ามกลางสวนผลไม้ ริมลำธาร น้ำใสไหลเย็น กิจกรรมล่องแพ เปียกปูน เหมาะแก่การพาครอบครัวมาพักผ่อน",
		history:
			"เดิมเป็นสวนผลไม้ส่งออก ปรับปรุงพื้นที่บางส่วนมาทำที่พักเพื่อให้คนเมืองได้มาสัมผัสวิถี ชาวสวนอย่างแท้จริง มุ่งเน้นการท่องเที่ยวเชิงนิเวศ",
		types: [OrchardType.Stay, OrchardType.Tour, OrchardType.Sell],
		status: DurianStatus.Out,
		lat: 12.6114,
		lng: 102.1039,
		ownerId: "owner3",
		address: "55/5 หมู่ 10 ต.พลับพลา อ.เมือง จ.จันทบุรี 22000",
		isMixedAgro: true,
		additionalCrops: ["rambutan", "mangosteen", "banana"],
		socialMedia: {
			facebook: "https://facebook.com/chantimahomestay",
			line: "https://line.me/ti/p/~chantima",
		},
		images: [
			"https://picsum.photos/400/300?random=301",
			"https://picsum.photos/400/300?random=302",
			"https://picsum.photos/400/300?random=303",
			"https://picsum.photos/400/300?random=304",
			"https://picsum.photos/400/300?random=305",
			"https://picsum.photos/400/300?random=306",
			"https://picsum.photos/400/300?random=307",
			"https://picsum.photos/400/300?random=308",
			"https://picsum.photos/400/300?random=309",
			"https://picsum.photos/400/300?random=310",
			"https://picsum.photos/400/300?random=311",
			"https://picsum.photos/400/300?random=312",
			"https://picsum.photos/400/300?random=313",
			"https://picsum.photos/400/300?random=314",
			"https://picsum.photos/400/300?random=315",
		],
		videos: [],
		hasPackage: false,
		packages: [],
		hasAccommodation: true,
		accommodations: [
			{
				id: "acc_tent",
				name: "เต็นท์กระโจม ริมน้ำ (2 ท่าน)",
				price: 800,
				quantity: 10,
				images: ["https://picsum.photos/400/300?random=302"],
			},
			{
				id: "acc_bung",
				name: "บ้านดิน (2 ท่าน)",
				price: 1500,
				quantity: 5,
				images: ["https://picsum.photos/400/300?random=303"],
			},
			{
				id: "acc_fam",
				name: "บ้านเรือนไทย (10 ท่าน)",
				price: 5000,
				quantity: 1,
				images: ["https://picsum.photos/400/300?random=304"],
			},
		],
	},
	{
		id: 4,
		name: "สวนภูเขาไฟศรีสะเกษ (ลุงบุญ)",
		description:
			"ทุเรียนภูเขาไฟ กลิ่นไม่ฉุน เนื้อแห้ง กรอบนอก นุ่มใน หวานมัน ของดีเมืองศรีสะเกษ ที่ใครๆ ก็ต้องลอง",
		history:
			"สวนของเราปลูกบนดินภูเขาไฟเก่า ทำให้มีแร่ธาตุอุดมสมบูรณ์ ทุเรียนที่ได้จึงมีรสชาติเป็นเอกลักษณ์ ได้รับการรับรอง GI (Geographical Indication)",
		types: [OrchardType.Sell],
		status: DurianStatus.Reserved,
		lat: 15.1186,
		lng: 104.3216,
		ownerId: "owner4",
		address: "88 หมู่ 8 ต.พราน อ.ขุนหาญ จ.ศรีสะเกษ 33150",
		isMixedAgro: false,
		additionalCrops: [],
		socialMedia: {
			facebook: "https://facebook.com/sisaketlava",
			tiktok: "https://tiktok.com/@sisaketlava",
		},
		images: [
			"https://picsum.photos/400/300?random=401",
			"https://picsum.photos/400/300?random=402",
			"https://picsum.photos/400/300?random=403",
			"https://picsum.photos/400/300?random=404",
			"https://picsum.photos/400/300?random=405",
			"https://picsum.photos/400/300?random=406",
			"https://picsum.photos/400/300?random=407",
			"https://picsum.photos/400/300?random=408",
		],
		videos: [],
		hasPackage: false,
		packages: [],
		hasAccommodation: false,
		accommodations: [],
	},
	{
		id: 5,
		name: "Laplae Secret Garden",
		description: "สวนลับแล อุตรดิตถ์ ทุเรียนหลงลับแล หลินลับแล ต้นตำรับ บนดอยสูง อากาศดีตลอดปี",
		history:
			"สืบทอดจากรุ่นสู่รุ่น ปลูกแบบธรรมชาติบนภูเขาสูง การขนส่งต้องใช้มอเตอร์ไซค์วิบากเท่านั้น ท้าทายแต่คุ้มค่าความอร่อย",
		types: [OrchardType.Sell, OrchardType.Tour, OrchardType.Cafe],
		status: DurianStatus.Available,
		lat: 17.6201,
		lng: 100.0935,
		ownerId: "owner5",
		address: "ต.แม่พูล อ.ลับแล จ.อุตรดิตถ์ 53130",
		isMixedAgro: true,
		additionalCrops: ["longkong", "pineapple"],
		socialMedia: {
			facebook: "https://facebook.com/laplaesecret",
			instagram: "https://instagram.com/laplaesecret",
		},
		images: [
			"https://picsum.photos/400/300?random=501",
			"https://picsum.photos/400/300?random=502",
			"https://picsum.photos/400/300?random=503",
			"https://picsum.photos/400/300?random=504",
			"https://picsum.photos/400/300?random=505",
			"https://picsum.photos/400/300?random=506",
			"https://picsum.photos/400/300?random=507",
			"https://picsum.photos/400/300?random=508",
			"https://picsum.photos/400/300?random=509",
			"https://picsum.photos/400/300?random=510",
		],
		videos: [],
		hasPackage: false,
		packages: [],
		hasAccommodation: false,
		accommodations: [],
	},
];
